export const Route = {
  Home: 'Home',
  Test: 'Test',
  Tabs: 'Tabs',
  SelectStore: 'SelectStoreScreen',
  AuthenticationHome: 'auth',
  AuthLanding: 'auth/AuthLanding',
  VerifyPhoneNumberScreen: 'auth/VerifyPhoneNumberScreen',
  VerifyVerificationCodeScreen: 'auth/VerifyVerificationCodeScreen',
  LoginSuccessScreen: 'auth/LoginSuccessScreen',
  ScanHome: 'scan',
  ScanLanding: 'scan/ScanLanding',
  SubscriptionHome: 'subscription',
  SubscriptionLanding: 'subscription/SubscriptionLanding',
  LoyaltyHome: 'loyalty',
  LoyaltyLanding: 'loyalty/LoyaltyLanding',
  ItemSelect: 'order/ItemSelect',
  CheckoutHome: 'checkout',
  MyCart: 'checkout/MyCart',
  PaymentOptions: 'checkout/PaymentOptions',
  AddNewCard: 'checkout/AddNewCard',
  UpdateCardInfo: 'checkout/UpdateCardInfo',
};
